title: <p align="center"> Sovia I Pakpahan </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="https://https://www.linkedin.com/in/sovia-i-pakpahan-b486b726a/">LinkedIn</a> |
  <a href="https://https://github.com/soviapakpahan02">GitHub</a>
  </p>
  
  <p align="justify">
  I am an Undergraduate Statistics Student at Diponegoro University.
  <br><br>
  I am currently a Data Analytics student at MSIB Zenius.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
